global:
  scrape_interval: 15s  # Metriklerin ne sıklıkla toplanacağı (default: 15s)

scrape_configs:
  - job_name: "redis_exporter"
    static_configs:
      - targets: [localhost:9121]  # Redis Exporter'ın bulunduğu adres ve port
